name: build-test

on:
  push:
    # push to main branch will triger build-test-publish-deploy
    branches-ignore:
	  - main
  #all pull request
  pull_request:

jobs:
  build:
    runs-on: windows-latest #use remote Runner

	steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal