## triggered when committed to a branch (except main, cannot committed to main branch directly)
## triggered when created a pull request
name: build-test

on:
  push:
    # PR merge to main branch will triger build-test-publish-deploy_merge
    branches-ignore:
      - main
  #all pull request
  pull_request:

jobs:
  build:
    runs-on: windows-latest #use remote Runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal